const newsBiases = {
    "cnn.com": { verdict: "Leans left" },
    "nytimes.com": { verdict: "Leans left" },
    "foxnews.com": { verdict: "Right" },
    "washingtonpost.com": { verdict: "Leans left" },
    "usatoday.com": { verdict: "Leans left" },
    "wsj.com": { verdict: "Leans right" },
    "latimes.com": { verdict: "Leans left" },
    "chicagotribune.com": { verdict: "Centrist" },
    "bostonglobe.com": { verdict: "Left" },
    "theatlantic.com": { verdict: "Left" },
    "politico.com": { verdict: "Leans left" },
    "reuters.com": { verdict: "Centrist" },
    "ap.com": { verdict: "Leans left" },
    "politico.com": { verdict: "Leans left" },
    "bbc.com": { verdict: "Centrist" },
    "dailywire.com": { verdict: "Right" },
    "forbes.com": { verdict: "Centrist" },
    "dailymail.co.uk": { verdict: "Right" },
    "msnbc.com": { verdict: "Left" },
    "economist.com": { verdict: "Leans left" },
    "theatlantic.com": { verdict: "Left" },
    "newyorker.com": { verdict: "Left" },
    "theguardian.com": { verdict: "Leans left" },
    "independent.co.uk": { verdict: "Leans left" },
    "cbc.ca": { verdict: "Leans left" },
    "cbsnews.com": { verdict: "Leans left" },
    "vox.com": { verdict: "Left" },
    "thehill.com": { verdict: "Centrist" },
    "bloomberg.com": { verdict: "Left leaning" },
    "huffpost.com": { verdict: "Left" },
    "motherjones.com": { verdict: "Left" },
    "slate.com": { verdict: "Left" },
    "thedailybeast.com": { verdict: "Left" },
    "npr.com": { verdict: "Leans left" },
    "nypost.com": { verdict: "Leans right" },
    "washingtonexaminer.com": { verdict: "Leans right" },
    "washingtontimes.com": { verdict: "Leans right" },
    "nationalreview.com": { verdict: "Right" },
    "thefederalist.com": { verdict: "Right" },
    "dailycaller.com": { verdict: "Right" },
    "breitbart.com": { verdict: "Right" },
    "newsmax.com": { verdict: "Right" },
    "theepochtimes.com": { verdict: "Leans right" },
    "lemonde.fr": { verdict: "Leans left" },
    "timesofindia.indiatimes.com": { verdict: "Centrist" },
    "thehindu.com": { verdict: "Leans left" },
    "thewire.in": { verdict: "Right" },
    "aljazeera.com": { verdict: "Leans left" },
    "lapresse.ca": { verdict: "Leans left" },
    "ledevoir.com": { verdict: "Leans left" },
    "theglobeandmail.com": { verdict: "Centrist" },


    // add more as you go!
};